#!/bin/bash

# NOTE: Better to have UPX if you want to build the lowest possible executable.

set -e

ADDFLAGS=""
COMPRESS=1

show_help() {
	echo "Usage: $0 [OPTION] [ARG]"
	echo
	echo "       Common flags:"
	echo
	echo "  -h,  --help              Show this help message and exit."
	echo "  -d,  --debug             Build the program in debug mode."
	echo
	echo "  -gd, --graphical-debug   Build the program with GraphicDebugging"
	echo
	echo "       OVERRIDE flags:"
	echo
	echo "  -n,  --no-compression    Don't apply any additional compression to compiled executable"
	echo "  -f,  --force-compression Force compression on compiled executable"
	echo
	echo "  Note: If no flags are given, the program will be built in release mode with extra compression afterwards."
	echo
}

# To build        Debug - use `./autobuild -d`
# To build GraphicDebug - use `./autobuild -d X`
for arg in "$@"; do
    case $arg in
        -d|--debug) 
            ADDFLAGS="$ADDFLAGS DEBUG=1"
            COMPRESS=0 ;;

		-gd|--graphical-debug)
			ADDFLAGS="$ADDFLAGS DEBUG=1 GRDBG=1"
			COMPRESS=0 ;;

        -h|--help)
            show_help
            exit 0 ;;
        
        -n|--no-compression)
            echo Will not compress compiled executable.
            COMPRESS=0 ;;

		-f|--force-compression)
			echo Will force compression on compiled executable
			COMPRESS=1 ;;

        -*|--*)
            echo "Unknown option $arg"
            show_help
            exit 1
            ;;

        *)
            break ;;
    esac
done

# Just build with config in Makefile
make clean && make $ADDFLAGS

# Compress if not building Debug.
if [[ $COMPRESS = 1 ]]; then
	# Stripping everything that isn't required to launch the app
	strip -x -X -s -R .gnu.version -R .gnu.version_r. output/main

	if command -p which upx; then
		echo "UPX found, proceeding to compress the binary..."
		upx --overlay=strip --best --compress-icons=3 --no-reloc --all-methods --all-filters --no-lzma output/main
		exit 0
	else
		echo "UPX not found. Exiting..."
		exit 0
	fi
fi

exit 0