#!/bin/bash

# NOTE: Better to have UPX.

set -e +x

# Just build with config in Makefile
make clean && make

# Stripping everything that isn't required to launch the app
strip -x -X -s -R .gnu.version -R .gnu.version_r. output/main

if command -p which upx; then
    echo "UPX found, proceeding to compress the binary..."
    upx --best --compress-icons=3 --ultra-brute output/main
else
    echo "UPX not found. Exiting..."
    exit 0
fi