name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: dependency_install
      run: sudo apt-get install libsfml-dev
    - name: test_all
      run: ./autotest
