name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: dependency_install
      run: sudo apt update && sudo apt-get install libsfml-dev
    - name: build
      run: ./autobuild
